### ISSUE TITLE
Error When Going to Menu Items

### ISSUE THREAD

**Issue by abhays72** [solomonshalom/virtual-event-starter-kit#4]
- [x] Followed setup instructions in README.md

When you click on any of the top menu bar items, this error is shown.
<img width="1202" alt="error message" src="https://user-images.githubusercontent.com/63835821/158212090-5f065cef-9b64-4ba8-a641-4dc4956d072e.png">

@solomonshalom please look into the cause of this issue

**Comment by solomonshalom** [comment]
Hey, @abhays72 are you running this on localhost because I am not facing this issue while running it as a production build.

**Comment by abhays72** [comment]
yes its a problem when running on localhost

> Hey, @abhays72 are you running this on localhost because I am not facing this issue while running it as a production build. Please check your ENV files as well as revert any changes you might have done before deploying it, this might work.

**Comment by solomonshalom** [comment]
If that is the issue, just revert any changes you might have done and re-deploy the project.
